### ISSUE TITLE
trades insurance form to be passed known values

### ISSUE THREAD

**Issue by octochimp** [appsuite-com-au/gossamer#2]
we have 30,000 trades leads. For each we have 'trade', 'state', 'company', 'phone', 'email'

When providing those new prospects with a link for a new quote, it would be good if we can include the known values in the link, to partially pre-complete the form. 

e.g. allrisk.com.au/trades-insurance-quote/lead/{{trade}}/{{state}}/{{company}}/{{phone}}/{{email}}

**Comment by adamweaver** [comment]
Wrong repo
